language: php
php:
  - '7.0'
  - nightly
before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - composer require phpunit/phpunit
  - composer require satooshi/php-coveralls
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover ./build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v